### ISSUE TITLE
"Your project config YAML files contain pending changes."

### ISSUE THREAD

**Issue by andrewfairlie** [fortrabbit/craft-auto-migrate#12]
After a deploy I see that my changes applied correctly but I get a message on Craft of "Your project config YAML files contain pending changes." which is trying to revert back to the earlier version.

**Comment by ostark** [comment]
Does it provide further information about the affected files?

---

I can imagine the issue can occur when you remove a field or section. 
Newer versions of Craft Auto Migrate will remove all project config files before deploying it to the actual web space.
If you have an older project you may need to delete all .yaml files and redeploy your changes.

**Comment by dgaidula** [comment]
I am seeing the same thing with both Craft 3.9+ and 4.5+. I think they've made a change whereby if the project.yaml is missing it just recreates a new one, but instead of using what's in the db it's using the last know backup of the 'on server' files. I think with this new behavior, you actually want to 'keep' the project.yaml file. I am going to do more testing and will report back on this issue.

**Comment by dgaidula** [comment]
okay, I just spent the last hour testing this with a site that has both a staging and production universal app. I don't have any professional stack apps so I can't test it, but I think I have solved the issue. (Also, note that both of the apps that I tested were older apps that I Inherited and were never using git deployment until I just upgraded them.)

Both Apps: Craft 3.9.4 with allowAdminChanges = false which should put the project config system into read-only mode.

Okay so here is what I found.

You need to delete the following .yaml files on the apps that you intended to manage via git deploy. 
`storage/config-deltas/*.yaml*`
`storage/config-backups/*.yaml*`

then make sure that the containers have the environment variable
`KEEP_PROJECT_CONFIG=1`

and then the CP will report 'no pending changes' after each push with all changes applied as you would expect.

To be sure that I wasn't losing my mind, I also carefully set KEEP_PROJECT_CONFIG=0 so default behavior and deleted all yaml files but Craft is now writing a new project.yaml file based on the pre-deploy state. one thing, I did notice is that even though allowAdminChanges = false Craft is still writing a set of delta .yaml files no matter what, so I think when project.yaml is missing it uses these previous deltas to write a new one. (This would seem to be a change in Craft's behavior since v2.5.0 of craft-auto-migrate was released and deleting the project.yaml was introduced to solve this CP reapply issue.)

The other thing to keep in mind, is that every now and then you may have to set allowAdminChanges = true to troubleshoot something which will cause Craft to write a new set of deltas and backups of the project files that will now be out of sync and create a new loop of this behavior. The only thing I can see is perhaps a cron that would make sure to sweep all yaml files from config-deltas and config-backups unless there is a way for a script to run on the app container pre-deploy.

**Comment by ostark** [comment]
Thanks for investigation.
I'll try reproduce it.

**Comment by ostark** [comment]
If I understand the code correctly, the .yaml files you mentioned are not used to identify pending changes:
https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L645-L685

**Comment by dgaidula** [comment]
I do see that, perhaps deleting those was a red herring. I do know for sure that turning on 
`KEEP_PROJECT_CONFIG=1`

stopped all the cp madness with the multiple Craft 3 installs that I have.

It could also be that there is some type of yii framework caching of files at work.

Note that I have only tested with Craft 3, I did a quick comparison and the code is different between 3 & 4 wrt to ProjectConfig.php and its internals.

The behavior as I describe is real and verified amongst several installs over the weekend.

Another thing to note is the following code:

https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L652-L660
https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L549-L560

and in particular function getCurrentWorkingConfig

I now suspect the whole delete 'project.yaml' file was another red herring or edge case. I didn't start having problems with auto migrate until that was introduced. Again I have a mix of Craft 3 & 4 all updated to PHP 8.2 exhibiting this behavior.

The easy thing is to just include a note saying: "if you're having issues, try this..." now that I have a working solution I just don't have the time to delve into Craft src at the moment. Later this week when I do some work on the Craft 4 sites, I'll post if the same technique solves their issues as well.

**Comment by dgaidula** [comment]
also I just looked at:

https://github.com/fortrabbit/craft-auto-migrate/issues/7

and see that you note the following assumption:

"Craft will regenerate the entire folder structure from the database if config/project/project.yaml does not exist."

Craft is definitely not generated project.yaml from DB when missing. In my experiments, it never matched the current state of the DB. It would always match the pre-applied state of the DB. So it is definitely getting that from a file cache somewhere.

**Comment by dgaidula** [comment]
so here are the lines in Craft 3 showing that it's check the cache and not writing from the DB. Note that the version of Craft 3 must be > 3.4.4 and then it reads from cache and not the DB.

https://github.com/craftcms/cms/blob/3.8/src/services/ProjectConfig.php#L1886-L1908

Craft 4 same thing, reads from cache as a priority and not DB. So the caches are not getting updated when auto-migrate applies the config changes? 
https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L1803-L1831

**Comment by ostark** [comment]
Sorry for the late reply. Is there anything to do?

**Comment by dgaidula** [comment]
I just checked a sample of my Craft 3 and 4 sites that I have been pushing changes to since Oct 2023 with no issues. 

The 3 installs are `KEEP_PROJECT_CONFIG=1`

and the 4 installs are `KEEP_PROJECT_CONFIG=0` which is the default.

Maybe just add a note as part of install/setup first time to delete everything on both local and remote copies from these folders:
```
storage/config-deltas/*.yaml*
storage/config-backups/*.yaml*
```

and then if Craft 3 `KEEP_PROJECT_CONFIG=1`

This procedure is now part of my notes for upgrading and taking over old Craft setups and I haven't had any issues since. Some very old installs have that 'backups' folder and some do not.

**Comment by pheeque1** [comment]
@dgaidula 

Thanks for keeping us updated on the results of your detailed research. We've included your notes as [part of the README](https://github.com/fortrabbit/craft-auto-migrate#troubleshooting) to help others.
